HTTP_PORT: "8080"
GRPC_PORT: "8081"
OMDB_KEY: "faf7e5bb&s"
OMDB_URL: "http://www.omdbapi.com/"

MYSQL_USERNAME: "root"
MYSQL_PASSWORD: "password"
MYSQL_HOST: "127.0.0.1"
MYSQL_PORT: "3306"
MYSQL_DBNAME: "omdb"
