// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.15.8
// source: core/omdbCore.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Searchword string `protobuf:"bytes,1,opt,name=searchword,proto3" json:"searchword,omitempty"`
	Page       int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_omdbCore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_omdbCore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_core_omdbCore_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetSearchword() string {
	if x != nil {
		return x.Searchword
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search       []*SearchEntry `protobuf:"bytes,1,rep,name=Search,proto3" json:"Search,omitempty"`
	TotalResults string         `protobuf:"bytes,2,opt,name=totalResults,proto3" json:"totalResults,omitempty"`
	Response     string         `protobuf:"bytes,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *SearchReply) Reset() {
	*x = SearchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_omdbCore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReply) ProtoMessage() {}

func (x *SearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_core_omdbCore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReply.ProtoReflect.Descriptor instead.
func (*SearchReply) Descriptor() ([]byte, []int) {
	return file_core_omdbCore_proto_rawDescGZIP(), []int{1}
}

func (x *SearchReply) GetSearch() []*SearchEntry {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *SearchReply) GetTotalResults() string {
	if x != nil {
		return x.TotalResults
	}
	return ""
}

func (x *SearchReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type SearchEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Year   string `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	ImdbID string `protobuf:"bytes,3,opt,name=imdbID,proto3" json:"imdbID,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Poster string `protobuf:"bytes,5,opt,name=Poster,proto3" json:"Poster,omitempty"`
}

func (x *SearchEntry) Reset() {
	*x = SearchEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_omdbCore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEntry) ProtoMessage() {}

func (x *SearchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_core_omdbCore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEntry.ProtoReflect.Descriptor instead.
func (*SearchEntry) Descriptor() ([]byte, []int) {
	return file_core_omdbCore_proto_rawDescGZIP(), []int{2}
}

func (x *SearchEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchEntry) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *SearchEntry) GetImdbID() string {
	if x != nil {
		return x.ImdbID
	}
	return ""
}

func (x *SearchEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchEntry) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

type SingleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SingleRequest) Reset() {
	*x = SingleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_omdbCore_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRequest) ProtoMessage() {}

func (x *SingleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_omdbCore_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRequest.ProtoReflect.Descriptor instead.
func (*SingleRequest) Descriptor() ([]byte, []int) {
	return file_core_omdbCore_proto_rawDescGZIP(), []int{3}
}

func (x *SingleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SingleRating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *SingleRating) Reset() {
	*x = SingleRating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_omdbCore_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleRating) ProtoMessage() {}

func (x *SingleRating) ProtoReflect() protoreflect.Message {
	mi := &file_core_omdbCore_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleRating.ProtoReflect.Descriptor instead.
func (*SingleRating) Descriptor() ([]byte, []int) {
	return file_core_omdbCore_proto_rawDescGZIP(), []int{4}
}

func (x *SingleRating) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SingleRating) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SingleReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rated      string          `protobuf:"bytes,1,opt,name=Rated,proto3" json:"Rated,omitempty"`
	Released   string          `protobuf:"bytes,2,opt,name=Released,proto3" json:"Released,omitempty"`
	Runtime    string          `protobuf:"bytes,3,opt,name=Runtime,proto3" json:"Runtime,omitempty"`
	Genre      string          `protobuf:"bytes,4,opt,name=Genre,proto3" json:"Genre,omitempty"`
	Director   string          `protobuf:"bytes,5,opt,name=Director,proto3" json:"Director,omitempty"`
	Writer     string          `protobuf:"bytes,6,opt,name=Writer,proto3" json:"Writer,omitempty"`
	Actors     string          `protobuf:"bytes,7,opt,name=Actors,proto3" json:"Actors,omitempty"`
	Plot       string          `protobuf:"bytes,8,opt,name=Plot,proto3" json:"Plot,omitempty"`
	Language   string          `protobuf:"bytes,9,opt,name=Language,proto3" json:"Language,omitempty"`
	Country    string          `protobuf:"bytes,10,opt,name=Country,proto3" json:"Country,omitempty"`
	Awards     string          `protobuf:"bytes,11,opt,name=Awards,proto3" json:"Awards,omitempty"`
	Ratings    []*SingleRating `protobuf:"bytes,12,rep,name=Ratings,proto3" json:"Ratings,omitempty"`
	Metascore  string          `protobuf:"bytes,13,opt,name=Metascore,proto3" json:"Metascore,omitempty"`
	ImdbRating string          `protobuf:"bytes,14,opt,name=imdbRating,proto3" json:"imdbRating,omitempty"`
	ImdbVotes  string          `protobuf:"bytes,15,opt,name=imdbVotes,proto3" json:"imdbVotes,omitempty"`
	DVD        string          `protobuf:"bytes,16,opt,name=DVD,proto3" json:"DVD,omitempty"`
	BoxOffice  string          `protobuf:"bytes,17,opt,name=BoxOffice,proto3" json:"BoxOffice,omitempty"`
	Production string          `protobuf:"bytes,18,opt,name=Production,proto3" json:"Production,omitempty"`
	Website    string          `protobuf:"bytes,19,opt,name=Website,proto3" json:"Website,omitempty"`
	Response   string          `protobuf:"bytes,20,opt,name=Response,proto3" json:"Response,omitempty"`
	Title      string          `protobuf:"bytes,21,opt,name=Title,proto3" json:"Title,omitempty"`
	Year       string          `protobuf:"bytes,22,opt,name=Year,proto3" json:"Year,omitempty"`
	ImdbID     string          `protobuf:"bytes,23,opt,name=imdbID,proto3" json:"imdbID,omitempty"`
	Type       string          `protobuf:"bytes,24,opt,name=Type,proto3" json:"Type,omitempty"`
	Poster     string          `protobuf:"bytes,25,opt,name=Poster,proto3" json:"Poster,omitempty"`
}

func (x *SingleReply) Reset() {
	*x = SingleReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_omdbCore_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleReply) ProtoMessage() {}

func (x *SingleReply) ProtoReflect() protoreflect.Message {
	mi := &file_core_omdbCore_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleReply.ProtoReflect.Descriptor instead.
func (*SingleReply) Descriptor() ([]byte, []int) {
	return file_core_omdbCore_proto_rawDescGZIP(), []int{5}
}

func (x *SingleReply) GetRated() string {
	if x != nil {
		return x.Rated
	}
	return ""
}

func (x *SingleReply) GetReleased() string {
	if x != nil {
		return x.Released
	}
	return ""
}

func (x *SingleReply) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *SingleReply) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *SingleReply) GetDirector() string {
	if x != nil {
		return x.Director
	}
	return ""
}

func (x *SingleReply) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *SingleReply) GetActors() string {
	if x != nil {
		return x.Actors
	}
	return ""
}

func (x *SingleReply) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

func (x *SingleReply) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SingleReply) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SingleReply) GetAwards() string {
	if x != nil {
		return x.Awards
	}
	return ""
}

func (x *SingleReply) GetRatings() []*SingleRating {
	if x != nil {
		return x.Ratings
	}
	return nil
}

func (x *SingleReply) GetMetascore() string {
	if x != nil {
		return x.Metascore
	}
	return ""
}

func (x *SingleReply) GetImdbRating() string {
	if x != nil {
		return x.ImdbRating
	}
	return ""
}

func (x *SingleReply) GetImdbVotes() string {
	if x != nil {
		return x.ImdbVotes
	}
	return ""
}

func (x *SingleReply) GetDVD() string {
	if x != nil {
		return x.DVD
	}
	return ""
}

func (x *SingleReply) GetBoxOffice() string {
	if x != nil {
		return x.BoxOffice
	}
	return ""
}

func (x *SingleReply) GetProduction() string {
	if x != nil {
		return x.Production
	}
	return ""
}

func (x *SingleReply) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *SingleReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *SingleReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SingleReply) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *SingleReply) GetImdbID() string {
	if x != nil {
		return x.ImdbID
	}
	return ""
}

func (x *SingleReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SingleReply) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

var File_core_omdbCore_proto protoreflect.FileDescriptor

var file_core_omdbCore_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6f, 0x6d, 0x64, 0x62, 0x43, 0x6f, 0x72, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x43, 0x0a, 0x0d, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x22, 0x78, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x29, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7b, 0x0a, 0x0b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x59, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x59,
	0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x64, 0x62, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x64, 0x62, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x0c, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9b, 0x05, 0x0a, 0x0b, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6c, 0x6f, 0x74, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x50, 0x6c, 0x6f, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x41, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x07, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x53,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x52, 0x61, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6d, 0x64, 0x62, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x64, 0x62, 0x52, 0x61, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6d, 0x64, 0x62, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x64, 0x62, 0x56, 0x6f, 0x74, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x44, 0x56, 0x44, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x44,
	0x56, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6f, 0x78, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x42, 0x6f, 0x78, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x12,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x57, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x59, 0x65, 0x61, 0x72, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x64, 0x62, 0x49, 0x44, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x6d, 0x64, 0x62, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x18, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x68, 0x66, 0x61, 0x61, 0x2f, 0x6f, 0x6d, 0x64, 0x62, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_core_omdbCore_proto_rawDescOnce sync.Once
	file_core_omdbCore_proto_rawDescData = file_core_omdbCore_proto_rawDesc
)

func file_core_omdbCore_proto_rawDescGZIP() []byte {
	file_core_omdbCore_proto_rawDescOnce.Do(func() {
		file_core_omdbCore_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_omdbCore_proto_rawDescData)
	})
	return file_core_omdbCore_proto_rawDescData
}

var file_core_omdbCore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_omdbCore_proto_goTypes = []interface{}{
	(*SearchRequest)(nil), // 0: core.SearchRequest
	(*SearchReply)(nil),   // 1: core.SearchReply
	(*SearchEntry)(nil),   // 2: core.SearchEntry
	(*SingleRequest)(nil), // 3: core.SingleRequest
	(*SingleRating)(nil),  // 4: core.SingleRating
	(*SingleReply)(nil),   // 5: core.SingleReply
}
var file_core_omdbCore_proto_depIdxs = []int32{
	2, // 0: core.SearchReply.Search:type_name -> core.SearchEntry
	4, // 1: core.SingleReply.Ratings:type_name -> core.SingleRating
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_omdbCore_proto_init() }
func file_core_omdbCore_proto_init() {
	if File_core_omdbCore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_omdbCore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_omdbCore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_omdbCore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_omdbCore_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_omdbCore_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleRating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_omdbCore_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_omdbCore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_omdbCore_proto_goTypes,
		DependencyIndexes: file_core_omdbCore_proto_depIdxs,
		MessageInfos:      file_core_omdbCore_proto_msgTypes,
	}.Build()
	File_core_omdbCore_proto = out.File
	file_core_omdbCore_proto_rawDesc = nil
	file_core_omdbCore_proto_goTypes = nil
	file_core_omdbCore_proto_depIdxs = nil
}
